### ISSUE TITLE
Add BlueToolFixup

### ISSUE THREAD

**Issue by ffoxkawaii** [lzhoang2801/OpCore-Simplify#10]
On newer OS, intel bluetooth also need it to run

anyways thank you bro for helping me have a perfect hackintosh, this thing work way better than my other EFIs 😭

**Comment by lzhoang2801** [comment]
Could you build and test it again? It has been available previously at https://github.com/lzhoang2801/OpCore-Simplify/blob/main/Scripts/datasets/kext_data.py#L229C5-L238C7
