### ISSUE TITLE
your gpu is not supported

### ISSUE THREAD

**Issue by afgok1146** [lzhoang2801/OpCore-Simplify#18]
after i load in my hardware report i get this error "your gpu is not supported"
motherboard intel nuc 8i7hvk 32 gb ram  the gpu is amd vega m with 4gb hbm
and yet i am running sequioa os 15.0 opencore hackintosh

**Comment by lzhoang2801** [comment]
I didn't recall the integrated iGPU information of Kaby Lake G earlier, i will update it later

**Comment by lzhoang2801** [comment]
I didn't recall the discrete GPU information of Kaby Lake G earlier, i will update it later
