### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by BudDeuce** [lzhoang2801/OpCore-Simplify#19]
Whenever I try to get a hardware report using OpCore, it errors out after selecting the ACPI tables. Here is the full error and SysReport folder it generated. If you need any more details, I will be happy to help.
```
Traceback (most recent call last):
  File "C:\Users\BudDeuce\Downloads\OpCore-Simplify-main\OpCore-Simplify.py", line 339, in <module>
    o.main()
  File "C:\Users\BudDeuce\Downloads\OpCore-Simplify-main\OpCore-Simplify.py", line 306, in main
    self.k.select_required_kexts(hardware_report, smbios_model, macos_version, self.ac.patches)
  File "C:\Users\BudDeuce\Downloads\OpCore-Simplify-main\Scripts\kext_maestro.py", line 227, in select_required_kexts
    for controller_name, controller_props in hardware_report.get("Storage Controllers").items():
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
```

[SysReport.zip](https://github.com/user-attachments/files/17403562/SysReport.zip)

**Comment by lzhoang2801** [comment]
Please read the compatibility check section carefully

![Screenshot 2024-10-17 at 06 09 54](https://github.com/user-attachments/assets/f869bafe-6e8c-44d0-aa99-d7d76a3cc33a)

**Comment by BudDeuce** [comment]
I see that, but I wanted to know if that was an actual error so that others don't run into this in the future.

**Comment by lzhoang2801** [comment]
You need to replace the hard drive with a WD NVMe M.2 2230 SSD to install macOS

**Comment by BudDeuce** [comment]
Very nice work, I see you added a new commit relating to this.

Good luck to you and I'll let you know if I find anything else.
