### ISSUE TITLE
GenericUSBXHCI should not be used on AMD Desktops

### ISSUE THREAD

**Issue by Sooly890** [lzhoang2801/OpCore-Simplify#24]
GenericUSBXHCI, only applies to AMD laptops, it doesn't effect (and can ruin EFIs) on AMD Desktops. AMD Desktops only need ReleaseUSBOwnership

**Comment by lzhoang2801** [comment]
GenericUSBXHCI kext is only added based on confirmed PCI ID issues. It is not applied based on whether the system is a laptop or desktop. For more details, you can check here: https://github.com/lzhoang2801/OpCore-Simplify/blob/main/Scripts/kext_maestro.py#L234C1-L239C60

**Comment by Sooly890** [comment]
My bad - you clearly know what you're doing!
