### ISSUE TITLE
High battery drain with Ryzen 5 5500u!

### ISSUE THREAD

**Issue by ShashwanthN** [lzhoang2801/OpCore-Simplify#26]
I coulnt get sleep to work with my efi too! but ive noticed the battery drain is excessie in my chipset! its warm to the touch when the lid is closed!

**Comment by lzhoang2801** [comment]
Use [Smokeless_UMAF](https://github.com/DavidS95/Smokeless_UMAF/raw/main/UniversalAMDFormBrowser.zip) to change the setting Device Manager > AMD PBS > S3/Modern Standby Support to Modern Standby Support and try again
