### ISSUE TITLE
Enable option to choose newer Mac OS version despite unsupported GPU

### ISSUE THREAD

**Issue by Mudb0y** [lzhoang2801/OpCore-Simplify#27]
For advanced users, it would be nice to have an advanced option to enable support for newer Mac OS versions, despite the fact that you're using an older NVIDIA card.
I have a Quadro K620, which isn't technically supported but could be patched using OCLP. I'm planning to eventually get a newer card, but it would be nice if there was some sort of 'continue anyway' option to use a newer OS release if you want to experiment with unsupported / hacky solutions.

**Comment by lzhoang2801** [comment]
All the necessary configurations for using OpenCore Legacy Patcher are already in place, please help me review them
