### ISSUE TITLE
Option to skip "Compatibility Checker", to manually edit the efi afterwards.

### ISSUE THREAD

**Issue by holodrum** [lzhoang2801/OpCore-Simplify#28]
Hi, I was going to try this as it looks really interesting and promising, but I got stuck at the Compatibility Checker, as I'm using an AMD 6950 XT.

The issue is, it's a super easy fix, NootRX.kext makes the 6950 XT fully compatible, with hardware acceleration and everything working perfectly in macOS.
But OpCore refuses to continue as the 6950 XT is not compatible, and there's no option to continue anyway and then add the kext manually afterward.

An option to continue with the gathered efi, kexts, etc., for manual editing afterward would be a great feature, it could show a disclaimer about it being "unsupported", or only for "advanced users" or something along those lines.

It would also open up for OCLP setups, as a similar issue applies to certain unsupported cards that you can then manually add support for afterward (so similar to [this ](https://github.com/lzhoang2801/OpCore-Simplify/issues/27)open issue, although my specific situation is of course a bit different).

**Edit:** I just saw the section on the ReadMe that I clearly overlooked before, and there's a section: "Use AMD GPUs Navi 23 and Navi 21 with WhateverGreen (default will use NootRX", so I'm a bit confused as to why it's refusing to continue? 
I'm on an 12th gen intel CPU, but I don't plan on using the iGPU from that, only the 6950 XT.

**2nd edit:** I just tried my GTX 670 for testing, a natively supported card that does not need the Nvidia drivers, etc., on macOS, and that is showing up as "Unsupported" as well, so I'm really not sure what is going on here 🤔

**Comment by lzhoang2801** [comment]
Please send me the report.json file from the two scenarios you tried, and I will check it again

**Comment by lzhoang2801** [comment]
The lack of support for the RX 6950 XT at the moment is a peculiar issue. More details can be found at https://github.com/lzhoang2801/OpCore-Simplify/blob/main/Scripts/datasets/pci_data.py#L1066C1-L1067C1 and https://github.com/lzhoang2801/OpCore-Simplify/blob/main/Scripts/compatibility_checker.py#L104C1-L105C51

**Comment by holodrum** [comment]
Here's the report for the 6950 XT, the GTX 670 one sadly got wiped when I just created this one again! I renamed the file for the GTX one, but didn't realize that the entire SysReport folder gets wiped when creating a new report, so I'll have to switch out the GPU and make a new report when possible! Will see if it's possible to do today, if not, tomorrow :)

[Report.json](https://github.com/user-attachments/files/17421235/Report.json)

**Comment by lzhoang2801** [comment]
I've understood the issue now. The logic that the Compatibility Checker is applying to the laptop at the moment is that only the GPU card connected to the internal screen is working, which is why you're getting the unsupported result as mentioned. Let me make some adjustments to better fit this situation

**Comment by holodrum** [comment]
I see, that would explain why I'm having the issue with the GTX 670 as well, and I did have a feeling it could be something to do with using a laptop/eGPU setup! I'm assuming that you won't need the report for the 670 any longer then?

I really appreciate you looking into it, as someone who's hackintoshed a lot of machines over the years, I really would love to finally have a tool like this, as I'm always looking for ways to ease and automate the setup (the way I have on Windows and Linux), as I wanna spend less time tinkering with stuff, and more time being productive :)

**Comment by lzhoang2801** [comment]
Help me test with new commit https://github.com/lzhoang2801/OpCore-Simplify/commit/582e2ad2a26e68b058149dcda627903a5c96e59d

**Comment by holodrum** [comment]
Perfect, that did it! Awesome :D
I'll give it a shot tomorrow, see if I can get macOS installed on this machine with this tool! :)

**Comment by lzhoang2801** [comment]
"Whatever the outcome, just enjoy what an automated tool can accomplish!"
