### ISSUE TITLE
Temporary freezes (colored ball)

### ISSUE THREAD

**Issue by ehjuniorusp** [lzhoang2801/OpCore-Simplify#31]
APU: AMD Ryzen 5 5600G
Mainboard: AsRock A520M-HDV
16GB (2x8GB) DDR4

I finished install my Ryzentosh but..

There are freezes occurring for 15 to 20 seconds and then it releases. I don't know what could be causing this. These freezes have happened with several applications which makes it impossible to work.

**Comment by lzhoang2801** [comment]
There are some apps that need to use https://github.com/alvindimas05/AMDHelper for patching before use, and the APU must be set to a minimum of 2G VRAM. And if there's a bootarg ncpi=0x2000, remove it and try again

**Comment by ehjuniorusp** [comment]
About AMD Helper i know but in this case it os not about it. I will take a look in Vram and bootargs.

**Comment by lzhoang2801** [comment]
Adjust hidden settings such as VRAM size using Smokeless UMAF

Commonly, the VRAM size can be found at AMD CBS > NBIO > GFX, named UMA Frame Buffer Size.
If the setting is not visible, change Integrated Graphics Controller to Forces, and UMA Mode to Specified.

**Comment by ehjuniorusp** [comment]
Still same problem. There is something about graphics. I was using Google Chrome and everything was in red and freezing.
![IMG_20241021_091915](https://github.com/user-attachments/assets/9ef78d09-aa47-4c4a-b52c-50c894688d4c)
![IMG_20241021_091712](https://github.com/user-attachments/assets/15767ed7-b246-4b7c-86b3-ca1353984397)

**Comment by lzhoang2801** [comment]
Go to settings and disable GPU Rasterization to resolve the issue
<img width="1206" alt="Screenshot 2024-10-21 at 19 34 34" src="https://github.com/user-attachments/assets/c34f5a40-6061-401f-a02b-7f63045bdea3">

**Comment by ehjuniorusp** [comment]
In VRAM i did put 4GB. Is that ok or should i use 2GB instead?

**Comment by lzhoang2801** [comment]
2GB is enough, increasing it won’t hurt, but it's uncertain if it will solve any additional issues
