### ISSUE TITLE
AM4 w/5900X and Radeon 6800XT tool errors

### ISSUE THREAD

**Issue by Maestro31419** [lzhoang2801/OpCore-Simplify#33]
I followed the instructions to the letter. The sniffer created a machine report and ACPI list. Opcore Simplify seemed to read it successfully, but when choosing an OS (Big Sur) it came back with an error and would not create an EFI. I tried choosing several other OS's but had the same result - perhaps not the same error readout, but similar.

Below is a sequence of screen shots to illustrate the issue I'm having. I've tried creating the EFI on both a Windows 10 and Mac running Big Sur 11.7.3.

![Capture1](https://github.com/user-attachments/assets/762fbd60-1f84-4022-b762-ea6d0b20e280)
![Capture3](https://github.com/user-attachments/assets/6c4b2857-7189-4310-b695-788c0cd65367)
![Capture4](https://github.com/user-attachments/assets/b2f6498e-827f-409f-a480-4d6d43a4d7cf)

**Comment by lzhoang2801** [comment]
Please build again before reporting the error

**Comment by VToime** [comment]
Since RX 6800 XT cannot be used in Big Sur and below, should I try MacOS 12 or above?

**Comment by lzhoang2801** [comment]
I don't understand the issue you're facing. The RX 6800 XT has been supported since macOS Big Sur 11.4

https://support.apple.com/en-us/102363
<img width="877" alt="Screenshot 2024-10-22 at 11 26 00" src="https://github.com/user-attachments/assets/619d9e9d-4b6a-4d4d-8e99-10fa30986d39">
