### ISSUE TITLE
Incorrect 13600k quirks

### ISSUE THREAD

**Issue by ReginaLain** [lzhoang2801/OpCore-Simplify#34]
From what I could see:
1. HPET is disabled - critical error, because of this kernel panic.
2. Speedstep is not configured.
3. USB are not started, because of which USB 3 does not work, but this in general I can understand, because it is not quite in the competence of the script in this operation
I attach all configuration files for familiarization.
![Screenshot 2024-10-26 233433](https://github.com/user-attachments/assets/15dfc80c-1fe9-49fd-9383-cde4e73359a0)
[Report.json](https://github.com/user-attachments/files/17531935/Report.json)
https://disk.yandex.ru/d/Rdxi5LF10K-rPA

**Comment by lzhoang2801** [comment]
I don't understand the issues you're mentioning here.

1. ActivateHpetSupport quick description: 'Older boards like ICH6 may not always have HPET setting in the firmware preferences, this option tries to force enable it.' Why is it needed in this case?
2. How did you check that Speedtest is not working?
3. Have you mapped the USB?"

**Comment by lzhoang2801** [comment]
I don't understand the issues you're mentioning here.

1. ActivateHpetSupport quick description: 'Older boards like ICH6 may not always have HPET setting in the firmware preferences, this option tries to force enable it.' Why is it needed in this case?
2. How did you check that Speedtest is not working?
3. Have you mapped the USB?
