### ISSUE TITLE
Lenovo 15ABA7 incorrect quirks

### ISSUE THREAD

**Issue by ReginaLain** [lzhoang2801/OpCore-Simplify#35]
EnableWriteUnprotector was turned off and needs to be turned on
RebuildAppleMemoryMap should be disabled, because Lenovo laptops do not contain MTD table in ACPI.
Files attached
![Screenshot 2024-10-26 233433](https://github.com/user-attachments/assets/b5bfad6c-143f-4239-b6b6-4c022316e9c7)
[EFI.zip](https://github.com/user-attachments/files/17532184/EFI.zip)
[Report.json](https://github.com/user-attachments/files/17532187/Report.json)

**Comment by lzhoang2801** [comment]
Show me a screenshot of the panic. Using the EnableWriteUnprotector quirk is the worst option for AMD Ryzen systems

**Comment by ReginaLain** [comment]
> Show me a screenshot of the panic. Using the EnableWriteUnprotector quirk is the worst option for AMD Ryzen systems

![IMG_20241027_100858](https://github.com/user-attachments/assets/ffde58a6-e9b9-4cb5-a2fc-a78985a769b0)

**Comment by lzhoang2801** [comment]
If you're still using EnableWriteUnprotector without issues, then enjoy it. I've encountered problems with GPU acceleration not working with EnableWriteUnprotector. A better approach recommended here is to use the DevirtualiseMmio quirk and MmioWhitelist

**Comment by ReginaLain** [comment]
You're confused. EnableWriteUnprotector is not related to graphics by definition, so it cannot break it.
Nevertheless, your MMIO whitepaper suggestion was tested, it didn't work as expected.

**Comment by lzhoang2801** [comment]
Make sure you've identified the correct MMIO devirt. If you haven't encountered similar issues, consider it incorrect
