### ISSUE TITLE
Black screen after picking macOS Base System partition on T430

### ISSUE THREAD

**Issue by madafaka3** [lzhoang2801/OpCore-Simplify#37]
I'm getting a black screen on my ThinkPad T430 while I'm trying to boot Catalina from the EFI generated by Opcore.
CPU: i7-3610qm
Will provide EFI partition if necessary.

**Comment by lzhoang2801** [comment]
Send me your report

**Comment by madafaka3** [comment]
[EFI.zip](https://github.com/user-attachments/files/17555752/EFI.zip)
[SysReport.zip](https://github.com/user-attachments/files/17555762/SysReport.zip)

**Comment by madafaka3** [comment]
update: I got it to display something but now it just hangs on End RandomSeed no matter what macOS version I try

**Comment by lzhoang2801** [comment]
Inbox me via telegram @lzhoang2601
