### ISSUE TITLE
No supporting video card

### ISSUE THREAD

**Issue by nekomeowking** [lzhoang2801/OpCore-Simplify#38]
How to continue making efi without video card support?
!
[{116EDC83-82E9-4947-AE01-0EF194F6362B}](https://github.com/user-attachments/assets/ba8fcda9-1298-40ac-8f04-59c4690900ec)

![{E1BC1A14-73FF-4C62-A4FE-BD9DC785C233}](https://github.com/user-attachments/assets/ad6e5c5f-678f-4d28-a662-4699a739b51c)
After I do the enter, my hardware does not write and it turns out, what should I do?
Please help!:s

**Comment by lzhoang2801** [comment]
Add a few lines of code to help make it work

**Comment by nekomeowking** [comment]
What needs to be added to the code?

**Comment by TheLazyGeekGuy** [comment]
Same here, WX2100 is unsupported, but i managed to make it work.
How can i bypass GPU compatibility check ?

**Comment by TheLazyGeekGuy** [comment]
It is on another hackintosh under sonoma ... 
i ended to add "Lexa" architecture on compatible GPU.

**Comment by lzhoang2801** [comment]
> It is on another hackintosh under sonoma ... i ended to add "Lexa" architecture on compatible GPU.

At least please provide the report.json, config.plist, and a screenshot of 'About This Mac' so I can verify the issue more easily

**Comment by lzhoang2801** [comment]
> It is on another hackintosh under sonoma ... i ended to add "Lexa" architecture on compatible GPU.

Check it. https://github.com/lzhoang2801/OpCore-Simplify/commit/aff726b78528390022749da544822e4380f58424
