### ISSUE TITLE
fails to create report.json

### ISSUE THREAD

**Issue by mattyry2009** [lzhoang2801/OpCore-Simplify#40]
whenever i try to generate a system report it throws an error basically saying it cant create report.json, can somebody help?
<img width="426" alt="oops" src="https://github.com/user-attachments/assets/6f66aece-e2ee-4cd5-958c-7fe35b0ee1d2">

**Comment by lzhoang2801** [comment]
Can you use a Hardware Sniffer to create a report and dump ACPI tables, then manually drag the file and folder?
