### ISSUE TITLE
failed to create EFI

### ISSUE THREAD

**Issue by sivaprasad2003** [lzhoang2801/OpCore-Simplify#41]
cant able to create report.json and program is quiting after compatibility check using hardware sniffer manually 

![Screenshot 2024-11-03 064402](https://github.com/user-attachments/assets/fb0c91b2-4f85-42bc-ac42-55861bba6895)
![Screenshot 2024-11-03 064417](https://github.com/user-attachments/assets/55929d89-ae4d-42a8-b58b-388bfe69e664)

**Comment by lzhoang2801** [comment]
Are you ignoring the message 'No compatible GPU card for macOS was found!' at the bottom of the compatibility checker screen?
