### ISSUE TITLE
I use opcore-simplify custom efi,but always have error

### ISSUE THREAD

**Issue by freewinder-tech** [lzhoang2801/OpCore-Simplify#44]
my computer:  cpu : i5-10400f, GPU: rx580(2304) ,Mainboard: Msi H510m.
when i generate efi and copy it into esp ,then reboot ,the computer will stuck.detail in pic

![WechatIMG37](https://github.com/user-attachments/assets/c78323f8-e31e-4bb4-957a-00fcc8a2730d)

can anyone tell me what's wrong???thanks

**Comment by lzhoang2801** [comment]
Try a small change in the config.plist by disabling Booter -> Quirks -> SetupVirtualMap and try again

**Comment by hkyle7640** [comment]
i have the same problem and it still didn't work

**Comment by lzhoang2801** [comment]
> i have the same problem and it still didn't work

Provide the hardware information you are using

**Comment by freewinder-tech** [comment]
thanks ,issue is SetupVirtualMap.but i choose enable is ok.thanks again

**Comment by Imtiajrex** [comment]
@freewinder-tech just disabling the SetupVirtualMap solved your problem?
