### ISSUE TITLE
HP840 G5

### ISSUE THREAD

**Issue by Snake221982** [lzhoang2801/OpCore-Simplify#45]
Hi. What could be the problem? I do everything according to the instructions but I get this error when loading
![IMG_1024](https://github.com/user-attachments/assets/280ec903-8063-421d-88f0-8a4a83be2138)
![IMG_1025](https://github.com/user-attachments/assets/7d169649-549c-45cc-bf9d-051e4cb78a10)

**Comment by Snake221982** [comment]
[Report.json](https://github.com/user-attachments/files/17636364/Report.json)

**Comment by lzhoang2801** [comment]
I think it's missing input devices, which is causing the error you're experiencing. Use the new version of Hardware Sniffer (https://github.com/lzhoang2801/Hardware-Sniffer/releases/tag/1.5.8), build a new EFI, and try again.

**Comment by Snake221982** [comment]
> Я думаю, что отсутствуют устройства ввода, что и вызывает ошибку, с которой вы столкнулись. Используйте новую версию Hardware Sniffer ( https://github.com/lzhoang2801/Hardware-Sniffer/releases/tag/1.5.8 ), создайте новый EFI и попробуйте снова.



> I think it's missing input devices, which is causing the error you're experiencing. Use the new version of Hardware Sniffer (https://github.com/lzhoang2801/Hardware-Sniffer/releases/tag/1.5.8), build a new EFI, and try again.

Should I use the CLI version or the regular one?

**Comment by lzhoang2801** [comment]
It only changes the usage method, it doesn’t affect the final result.

**Comment by Snake221982** [comment]
![IMG_1029](https://github.com/user-attachments/assets/0ab6f0a2-3a73-451d-8f7d-b7df2b663154)
![IMG_1030](https://github.com/user-attachments/assets/012a1ee4-175a-4f2d-a70a-7f6bc5a00deb)


Nothing has changed

**Comment by lzhoang2801** [comment]
Send me new report.json and config.plist

**Comment by Snake221982** [comment]
I found this EFI on the internet. with its help everything was installed. but since Opencore an old version and EFI was apparently created for other equipment, many functions do not work for me. regardless of whic Mac OS is installed. The wifi and bluetooth modules are detected, but they are inactive and its not possible to enable them. The buttons on the touchpad do not work and much more. But the fact is that the system is installed and works. But through the script for some reason it does not (((((

https://drive.google.com/drive/folders/1zIOfIud4uZvywI6qoMGGo1H-IYT8Gpui?usp=sharing

**Comment by lzhoang2801** [comment]
Select RTCAWAC in Customize ACPI Patch and try again

**Comment by Snake221982** [comment]
> Select RTCAWAC in Customize ACPI Patch and try again

Now the download is ongoing. Only the minimum version of the OS with which the download is carried out is Catalina. With other OS, the script reboots the laptop two minutes after the start of the download. In any case, now I will check how the installation goes and write. Thank you very much for your help

**Comment by lzhoang2801** [comment]
Use Unplugged to install macOS. Send me your ACPI Tables folder

**Comment by lzhoang2801** [comment]
For Catalina, you need to install AirportItlwm into /Library/Extensions instead of loading it through OC for WiFi to work. For UnPlugged, please read the README.
