### ISSUE TITLE
No bootloader or kexts files found in the product directory.

### ISSUE THREAD

**Issue by PeterSuh-Q3** [lzhoang2801/OpCore-Simplify#52]
It seems to be caused by downloading the latest version of OpenCorePkg, 1.03.
An error like this occurs during the build and the build cannot proceed.
Please tell me how to solve it.

####################################################################
#                        An Error Occurred                         #
####################################################################

Traceback (most recent call last):
  File "F:\_OpCore\OpCore-Simplify.py", line 347, in <module>
    o.main()
  File "F:\_OpCore\OpCore-Simplify.py", line 335, in main
    self.gathering_files(macos_version)
  File "F:\_OpCore\OpCore-Simplify.py", line 38, in gathering_files
    self.o.gather_bootloader_kexts(self.k.kexts, macos_version)
  File "F:\_OpCore\Scripts\gathering_files.py", line 204, in gather_bootloader_kexts
    if self.move_bootloader_kexts_to_product_directory(product_name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\_OpCore\Scripts\gathering_files.py", line 128, in move_bootloader_kexts_to_product_directory
    raise FileNotFoundError("No bootloader or kexts files found in the product directory.")
FileNotFoundError: No bootloader or kexts files found in the product directory.

Press Enter to continue...

**Comment by PeterSuh-Q3** [comment]
####################################################################
#                         OpCore Simplify                          #
####################################################################

Hardware Report: F:\_OpCore\Results\Report.json

* Hardware Compatibility:
   - Native macOS Version: Up to macOS Sequoia 15
   - Unsupported devices:
      1. Sound: 인텔(R) 디스플레이 오디오 (LC32G5xT(2- 인텔(R) 디스플레이 오디오)) (LC32G5xT(2- 인텔(R) 디스플레이 오디오))
* EFI Options:
   - macOS Version: macOS Sequoia 15 (24.99.99)
   - SMBIOS: iMac19,1

1. Select Hardware Report
2. Select macOS Version
3. Customize ACPI Patch
4. Customize Kexts
5. Customize SMBIOS Model
6. Build OpenCore EFI

Q. Quit

Select an option:

**Comment by lzhoang2801** [comment]
Fixed https://github.com/lzhoang2801/OpCore-Simplify/commit/706f33a909db833fa0806608e4e227889ca418c4

**Comment by PeterSuh-Q3** [comment]
> Fixed [706f33a](https://github.com/lzhoang2801/OpCore-Simplify/commit/706f33a909db833fa0806608e4e227889ca418c4)

Thank you for your real-time support.^^
