### ISSUE TITLE
This time we won't download any Kexts.

### ISSUE THREAD

**Issue by PeterSuh-Q3** [lzhoang2801/OpCore-Simplify#53]
The error is gone, but no Kexts are downloaded. 
I tried selecting AMFIPass.kext as a user choice, 
but only this gets downloaded, and nothing else gets downloaded.

![image](https://github.com/user-attachments/assets/fc9c8deb-b4c3-4aa3-94a4-3fd024bb20e5)

**Comment by lzhoang2801** [comment]
Remove folder OCK_Files and rebuild EFI

**Comment by PeterSuh-Q3** [comment]
> Remove folder OCK_Files and rebuild EFI

Yes, I deleted all the folders and started over again and it worked. Thank you.
