### ISSUE TITLE
About Intel(R) Display Audio...

### ISSUE THREAD

**Issue by Serena1432** [lzhoang2801/OpCore-Simplify#54]
I just want to ask a question:

*In your OpCore Simplifier tool, Intel(R) Display Audio is listed as "Unsupported". However as I know, this is the HDMI audio driver, and if I remember correctly, the HDMI audio output is actually supported by AppleALC and macOS itself. So it should be listed as "Supported", or at least partially with some patches, right?*

Or is that anything that I'm missing? If I told something wrong, please clarify to me.

![image](https://github.com/user-attachments/assets/3742d9eb-d469-4175-9676-8d8a3f62e422)

**Comment by lzhoang2801** [comment]
I need to crawl information related to Intel Smart Sound Technology to make this check more accurate. It’ll be soon.

**Comment by lzhoang2801** [comment]
It will work, just ignore this notification

**Comment by lzhoang2801** [comment]
Fixed https://github.com/lzhoang2801/OpCore-Simplify/commit/ef01b0bb3c22a22f2706cdd140cfa84d6bab747c
