### ISSUE TITLE
It doesn't work on my pc

### ISSUE THREAD

**Issue by StealKkak** [lzhoang2801/OpCore-Simplify#59]
When booting with an EFI created with Simplify, it stops at EXITBS:START, so I created it manually.
[EFI(Non-Simplify).zip](https://github.com/user-attachments/files/17788705/EFI.Non-Simplify.zip)
[ACPITables.zip](https://github.com/user-attachments/files/17788706/ACPITables.zip)
[EFI(Simplify).zip](https://github.com/user-attachments/files/17788707/EFI.Simplify.zip)
[Report.json](https://github.com/user-attachments/files/17788708/Report.json)

**Comment by StealKkak** [comment]
My PC information is in the report.json file.

**Comment by lzhoang2801** [comment]
Both configs are completely identical in Quirks and Patch. I'm not sure if this is exactly the issue you're facing

**Comment by Litemint09** [comment]
1. Try updating the bios to its latest version
2. Adjust the bios settings if applies to you
![Screenshot 2024-11-18 at 9 58 33 AM](https://github.com/user-attachments/assets/119b016a-dc7f-4da0-8a66-d54b1c7065a6)

**Comment by StealKkak** [comment]
This issue doesn't seem to be related to Quirks and Patch. The differences I found between the config.plist I created and the plist generated by simplify are in ACPI - Delete and Patch, and in Kernel - Add, Block, and Force.
