### ISSUE TITLE
Is there a way to use OpCore-Simplify under macOS?

### ISSUE THREAD

**Issue by kehyian** [lzhoang2801/OpCore-Simplify#62]
I know you can run the program using "OpCore-Simplify.command" but then you have to import a hardware report.
How can I get a hardware report under macOS ?

**Comment by jzrodriguez98** [comment]
> I know you can run the program using "OpCore-Simplify.command" but then you have to import a hardware report.
> 
> How can I get a hardware report under macOS ?

You just need to use Hardware Sniffer app available here https://github.com/lzhoang2801/Hardware-Sniffer
