### ISSUE TITLE
graphics

### ISSUE THREAD

**Issue by Sgorbikov** [lzhoang2801/OpCore-Simplify#64]
AMD Radeon RX 6950 XT  it is determined normally. it works incorrectly.it slows down very much.

**Comment by lzhoang2801** [comment]
Send me report.json, acpitables and config.plist

**Comment by Sgorbikov** [comment]
[config.zip](https://github.com/user-attachments/files/17811968/config.zip)
[Report.zip](https://github.com/user-attachments/files/17812066/Report.zip)

**Comment by lzhoang2801** [comment]
You need PCI Bridge ACPI Patch (use SSDTTime) for RX 6950 XT and new [config.plist.zip](https://github.com/user-attachments/files/17824068/config.plist.zip)

PCI Path: PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)
