### ISSUE TITLE
Add support for Broadcom Ethernet 

### ISSUE THREAD

**Issue by unitedastronomer** [lzhoang2801/OpCore-Simplify#65]
edit: I have rewritten it on the next comment.
<details>
<summary>List is based on supported by FakePCIIID kext on Catalina.</summary>
**Supported device-id(s)**:

Broadcom NetXtreme BCM5700 Gigabit Ethernet [14e4:1644]
Broadcom NetXtreme BCM5701 Gigabit Ethernet PCIe [14e4:1645]
Broadcom NetXtreme BCM5702 Gigabit Ethernet PCIe [14e4:1646]
Broadcom NetXtreme BCM5703 Gigabit Ethernet PCIe [14e4:1647]
Broadcom NetXtreme BCM5717 Gigabit Ethernet PCIe [14e4:1655]
Broadcom NetXtreme BCM5717 Gigabit Ethernet PCIe [14e4:1665]
Broadcom NetXtreme BCM5718 Gigabit Ethernet PCIe [14e4:1656]
Broadcom NetXtreme BCM5719 Gigabit Ethernet PCIe [14e4:1657]
Broadcom NetXtreme BCM5725 Gigabit Ethernet PCIe [14e4:1643]
Broadcom NetXtreme BCM5727 Gigabit Ethernet PCIe [14e4:16f3]
Broadcom NetXtreme BCM5761 10/100/1000BASE-T Ethernet [14e4:1688]
Broadcom NetXtreme BCM5762 Gigabit Ethernet PCIe [14e4:1687]
Broadcom NetXtreme BCM57760 Gigabit Ethernet PCIe [14e4:1690]
Broadcom NetXtreme BCM57764 Gigabit Ethernet PCIe [14e4:1642]
Broadcom NetXtreme BCM57767 Gigabit Ethernet PCIe [14e4:1683]
Broadcom NetLink BCM57781 Gigabit Ethernet PCIe [14e4:16b1]
Broadcom NetXtreme BCM57782 Gigabit Ethernet PCIe [14e4:16b7]
Broadcom NetLink BCM57785 Gigabit Ethernet PCIe [14e4:16b5]
Broadcom NetXtreme BCM57786 Gigabit Ethernet PCIe [14e4:16b3]
Broadcom NetXtreme BCM57787 Gigabit Ethernet PCIe [14e4:1641]
Broadcom NetLink BCM57788 Gigabit Ethernet PCIe [14e4:1691]
Broadcom NetLink BCM57790 Gigabit Ethernet PCIe [14e4:1694]
Broadcom NetLink BCM57791 Gigabit Ethernet PCIe [14e4:16b2]
Broadcom NetLink BCM57795 Gigabit Ethernet PCIe [14e4:16b6]
Broadcom NetLink BCM5785 Gigabit Ethernet [14e4:1699]
Broadcom NetLink BCM5785 Fast Ethernet [14e4:16a0]
Broadcom NetLink BCM5787M Gigabit Ethernet PCI Express [14e4:1693]
Broadcom Network Adapter [14e4:1689]
</details>

**Comment by lzhoang2801** [comment]
Help me check it https://github.com/lzhoang2801/OpCore-Simplify/commit/d81ff30da6db64c25ff18f8663d02db178001896

**Comment by lzhoang2801** [comment]
Why do we need to patch com.apple.iokit.CatalinaBCM5701Ethernet here? I also don't see it mentioned in OCLP, and the replace value you mentioned are you sure it's applicable for all devices?

https://www.applelife.ru/threads/patching-applebcm5701ethernet-kext.27866/page-4#post-564218
