### ISSUE TITLE
EFI making HTTPS Error

### ISSUE THREAD

**Issue by NissanVROOOMNISMO** [lzhoang2801/OpCore-Simplify#69]
![Screenshot 2024-11-22 171038](https://github.com/user-attachments/assets/d4555eac-42a4-450e-8c73-6f6859b80bc7)

Gets error when making EFI folder File "C:\Users\ibrah\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^                                             http_error_defaultbrah\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py",
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 504: Gateway Time-outhon313\Lib\urllib\request.py",
line 613, in ers\ibrah\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py"

**Comment by lzhoang2801** [comment]
Error 504 Gateway Time Out due to the connection to the server, not an issue with OpCore Simplify

**Comment by NissanVROOOMNISMO** [comment]
Will it be fixed?
