### ISSUE TITLE
HP Compaq Elite 8300 CMT with AMD RX 580 Successfully Running macOS 15.1 (Sequoia) with Graphics Acceleration

### ISSUE THREAD

**Issue by ylluminate** [lzhoang2801/OpCore-Simplify#70]
First, thank you for providing such an excellent tool for simplifying Hackintosh setups!  

I wanted to report a misstep in the tool's compatibility assessment and configuration regarding the HP Compaq 8300 CMT with an AMD RX 580 GPU.  

#### **Details:**

- The tool currently suggests that this system cannot run macOS versions higher than **12 Monterey**, but I have successfully installed and run **macOS 15.1 (Sequoia)** with full functionality.
- During the initial setup, the `config.plist` generated by the tool included the `-amd_no_dgpu_accel` boot argument.  
  - This boot argument **disables GPU acceleration** and causes a white screen when accelerated graphics are attempted.
  - Removing `-amd_no_dgpu_accel` and patching the root volume with **OpenCore Legacy Patcher** resolved the issue entirely.
  
#### **Steps Taken to Resolve:**
1. Removed `-amd_no_dgpu_accel` from `boot-args` in the `config.plist`.
2. Used OpenCore Legacy Patcher to apply post-install patches for GPU acceleration.
3. Rebooted, and the system now runs macOS 15.1 with full GPU acceleration and no issues observed so far.

#### **Request:**
- Please consider updating the compatibility notes for your tool to reflect that the HP Compaq 8300 CMT with an AMD RX 580 is capable of running macOS 15.1 (Sequoia).  
- It would also be helpful to adjust the default `config.plist` generated for such setups to avoid the inclusion of `-amd_no_dgpu_accel`, as it unnecessarily limits functionality.  

Thank you again for your fantastic work, and I hope this information helps improve the tool for others!

**Comment by lzhoang2801** [comment]
Move it to https://github.com/lzhoang2801/OpCore-Simplify/discussions/23
