### ISSUE TITLE
 stuck at SHA version information is missing in the sha_version.txt file.

### ISSUE THREAD

**Issue by lugnarm** [lzhoang2801/OpCore-Simplify#72]
####################################################################
#                        Check for Updates                         #
####################################################################

SHA version information is missing in the sha_version.txt file.
![Screenshot 2024-11-29 234450](https://github.com/user-attachments/assets/e61266a3-f27d-41a7-a4c1-45c09a037dea)

**Comment by lzhoang2801** [comment]
Please wait
