### ISSUE TITLE
[HELP] Kernel Panic on HP 470 G7 – Sonoma

### ISSUE THREAD

**Issue by JUser50** [lzhoang2801/OpCore-Simplify#74]
Hello,

I created this account to ask for help. I’m trying to install macOS Sonoma on my HP 470 G7 but I’m encountering a kernel panic during boot.

I’ve attached a screenshot of the kernel panic.
![IMG_6673](https://github.com/user-attachments/assets/9eb37c8c-dad7-4079-ba28-f11d453812e4)

Specs of the laptop:
HP 470 G7, Chipset: Comet Lake : 
	•	CPU: Intel Core i5-10210U (Comet Lake-U)
	•	Integrated GPU: Intel UHD Graphics
	•	Discrete GPU: AMD Radeon 530
	•	Monitor: 1600x900
	•	Storage: Samsung NVMe
	•	Wi-Fi: Intel Wi-Fi 6 AX201
[Report.txt](https://github.com/user-attachments/files/18101987/Report.txt)

I’d appreciate any guidance or suggestions to resolve this issue.

**Comment by lzhoang2801** [comment]
Follow https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start
