### ISSUE TITLE
get kernel panic .after reboot pc. 

### ISSUE THREAD

**Issue by arponascension1** [lzhoang2801/OpCore-Simplify#79]
hey. help me i get kernel. when i boot direct from hard drive. when i boot with usb it get no error,
[Pc report.zip](https://github.com/user-attachments/files/18135756/Pc.report.zip)

**Comment by lzhoang2801** [comment]
Please provide an image showing the error

**Comment by arponascension1** [comment]
![IMG_20241214_182914](https://github.com/user-attachments/assets/4f0428d5-1831-46a9-b09b-fa746d45d3fa)

**Comment by lzhoang2801** [comment]
Show me full screen

**Comment by arponascension1** [comment]
![Uploading IMG_20241214_222157.jpg …]()

**Comment by arponascension1** [comment]
![IMG_20241214_222157.jpg](https://github.com/user-attachments/assets/2f2b8789-9a81-4d05-b9ad-57f77d54ca64)

**Comment by lzhoang2801** [comment]
Send me your config.plist

**Comment by arponascension1** [comment]
[config.plist.zip](https://github.com/user-attachments/files/18138564/config.plist.zip)

**Comment by lzhoang2801** [comment]
Try it [config.plist.zip](https://github.com/user-attachments/files/18139357/config.plist.zip)

**Comment by arponascension1** [comment]
Problem is fixed but slow booting. Can you please fix it for me?
