### ISSUE TITLE
[Feature Request] Make it so u can disable unsupported stuff

### ISSUE THREAD

**Issue by hypermoist** [lzhoang2801/OpCore-Simplify#8]
Since i have a dual gpu system, it would be neat if you can make it so you can disable the unsupported GPUs (ex: RTX 3060) instead of the script out right saying your system is not supported.

**Comment by lzhoang2801** [comment]
Send me your report.json

**Comment by hypermoist** [comment]
[Report.json](https://github.com/user-attachments/files/17337284/Report.json)
Here is the attached Report.json

**Comment by lzhoang2801** [comment]
Could you re-export the report.json using the latest version of Hardware Sniffer? I have some updates that I need to check before incorporating them into OpCore Simplify

**Comment by lzhoang2801** [comment]
The issue will be resolved by rewriting the compatibility check. I will start working on it right now

**Comment by hypermoist** [comment]
[Report.json](https://github.com/user-attachments/files/17340532/Report.json)
Adding this just incase you still need it, sorry for late reply.

**Comment by lzhoang2801** [comment]
Please use [Report.json](https://github.com/user-attachments/files/17340710/Report.json) temporarily to build the EFI and add the bootarg nv_disable=1 to disable your NVIDIA discrete card. With the new version of Hardware Sniffer, I hope it includes the additional information I updated. I don't understand why it doesn't work on your machine

**Comment by hypermoist** [comment]
Yeah i used the latest 1.2.6 to make my above Report.Json, I'm not to sure why the tool says I'm not compatible, as i know removing the NVidia related args it then reports its compatible

**Comment by lzhoang2801** [comment]
Could you open Device Manager, locate your display -> Details -> Location Paths, and provide me with its value?

**Comment by hypermoist** [comment]
PCIROOT(0)#PCI(0100)#PCI(0000)
ACPI(_SB_)#ACPI(PC00)#ACPI(PEG1)#ACPI(PEGP) - RTX 3060


PCIROOT(0)#PCI(1B00)#PCI(0000)
ACPI(_SB_)#ACPI(PC00)#ACPI(RP21)#ACPI(PXSX) - RX 580

Here you are :)

**Comment by lzhoang2801** [comment]
You are providing the location paths of the GPU. I need those for the monitor. Could you please check again?

**Comment by hypermoist** [comment]
It would seem i do not have a location path under my Monitors Tab in device manager

**Comment by hypermoist** [comment]
I do have a device instance path? DISPLAY\AOC3402\5&31585CAA&0&UID521

**Comment by lzhoang2801** [comment]
That's the exact device I mentioned. However, could you provide the value of the BIOS Device Name or its location paths?

**Comment by hypermoist** [comment]
Under
MonitorName > Details there is no option of Bios Device Name and or Location paths

There is Parent Device stuff
Parent Device: PCI\VEN_1002&DEV_67DF&SUBSYS_E3531DA2&REV_E7\4&27741e03&0&00D8

Is this of any use?

**Comment by lzhoang2801** [comment]
It seems that the current method only works with Intel iGPU. Thank you!

**Comment by lzhoang2801** [comment]
You've discovered what I was looking for, thank you!

**Comment by hypermoist** [comment]
How's things going :D

**Comment by lzhoang2801** [comment]
I am trying to clean up a few things before updating for your case

**Comment by hypermoist** [comment]
No problem at all :)

**Comment by lzhoang2801** [comment]
Thank you for waiting, please try again with the commit https://github.com/lzhoang2801/OpCore-Simplify/commit/2dff881d6ac0d6075708d19f7bee2163a14624fd

**Comment by hypermoist** [comment]
I hadnt been able to test till now but latest version when pulling the script throws 
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\HYPERM~1\\AppData\\Local\\Temp\\tmpqyhh5tn_\\main\\OpCore-Simplify-main\\.github\\FUNDING.yml' -> 'G:\\OpCore-Simplify\\.github\\FUNDING.yml'

**Comment by hypermoist** [comment]
Tested it and the checks pass and it reads the json file properly thank you for fixing :D
