### ISSUE TITLE
First promblem

### ISSUE THREAD

**Issue by siudvnp1234** [lzhoang2801/OpCore-Simplify#80]
![image](https://github.com/user-attachments/assets/eca2a3f6-fcc7-4365-85a0-bca0c3b43c8a)

**Comment by lzhoang2801** [comment]
I haven't tested it on any Windows versions other than Windows 10 and Windows 11

**Comment by siudvnp1234** [comment]
I haven't tested it on any Windows versions other than Windows 10 and
Windows 11

вс, 15 дек. 2024 г., 09:31 Hoang Hong Quan ***@***.***>:
