### ISSUE TITLE
X570 w/5900X - fatal boot loop on install

### ISSUE THREAD

**Issue by Maestro31419** [lzhoang2801/OpCore-Simplify#82]
About 5 seconds into the installer booting up it gets stuck on the following:
[AHCI][PRT][0900050] Abort Commands::5381:Port 5 - called, deviceWithError 0, errcode = 0xe0030005

I note when I compare the config.plist generated by OpCore-Simplify to the current Dortania guide the generated config closely follows the guide, but not entirely.

Any guidance of where to start troubleshooting this problem would be much appreciated!

1. CPU:
   - AMD Ryzen 9 5900X 12-Core Processor: Up to macOS Sequoia 15
2. GPU:
   - AMD Radeon RX 6800 XT: Up to macOS Sequoia 15
      - Connected Monitors: LG ULTRAWIDE (DP), Beyond TV (HDMI)
3. Sound:
   - Logitech G933 Gaming Headset: Up to macOS Sequoia 15
      - Audio Endpoints: Speakers, Microphone
   - Realtek(R) Audio: Up to macOS Sequoia 15
      - Audio Endpoint: Speakers
   - Steinberg UR28M: Up to macOS Sequoia 15
      - Audio Endpoints: Line, Line
   - AMD High Definition Audio Device: Up to macOS Sequoia 15
      - Audio Endpoints: 5 - LG ULTRAWIDE, 4 - Beyond TV
4. Network:
   - Intel(R) I211 Gigabit Network Connection: Up to macOS Sequoia 15
5. Storage Controllers:
   - FCH SATA Controller [AHCI mode]: Up to macOS Sequoia 15
   - FCH SATA Controller [AHCI mode]_#1: Up to macOS Sequoia 15
   - P5 Plus NVMe PCIe SSD: Up to macOS Sequoia 15

Press Enter to continue...

**Comment by lzhoang2801** [comment]
Provide an image showing the error
