### ISSUE TITLE
Boot Frozen at AppleActuatorDevice::Start Entered (Dell 5310)

### ISSUE THREAD

**Issue by Prasety175** [lzhoang2801/OpCore-Simplify#85]
Hi.. I Have a problem with my laptop, it got stuck at AppleActuatorDevice::Start Entered and wont go anywhere from there 
Any ideas?

I attach my Config and Harware report too

[config.zip](https://github.com/user-attachments/files/18218543/config.zip)

[Report.zip](https://github.com/user-attachments/files/18218549/Report.zip)

**Comment by lzhoang2801** [comment]
Provide an image showing the error
