### ISSUE TITLE
error 1

### ISSUE THREAD

**Issue by parvindergithub** [lzhoang2801/OpCore-Simplify#88]
OpCore-Simplify.bat run as admin. got error 1  can`t understand  please help....
I am curious i want this for years  
your project is awesome  gr8 job

mention -- my bios is vanished ... trying to install no luck because of my laptop battery is dead...
OpCore-Simplify run without bios ???

![zz](https://github.com/user-attachments/assets/dfe02b02-337f-4274-9128-8dad28bca259)

**Comment by lzhoang2801** [comment]
Duplicate of #81
