### ISSUE TITLE
Kernel panic before booting macOS installer on AMD Ryzen 5900HX

### ISSUE THREAD

**Issue by TechBezza** [lzhoang2801/OpCore-Simplify#89]
So when i was going to boot to the MacOS Installer from OpenCore, it spits a kernel panic. I don't know why it happens but I can't boot into the MacOS Installer, I'm sorry if this report is unclear..

Laptop: Zenbook 14 OLED UM5401QA
OS: Windows 11
Version: 23H2, with MacOS Sonoma 14.4 Installer

Additional context
(i added AMDTscSync to the config ( does it conflict with the kexts).

**Comment by lzhoang2801** [comment]
Don't use AMDTscSync and provide a picture of error
