### ISSUE TITLE
Asus Rog Strix 

### ISSUE THREAD

**Issue by kamin067** [lzhoang2801/OpCore-Simplify#90]
congfuguration 
cpu :- AMD ryzen 7 4800h with radeon graphics
Dgpu nvidia RTX 3050

stuck at support.apple.com/mac/startup
![WhatsApp Image 2024-12-27 at 10 37 23 PM](https://github.com/user-attachments/assets/17bdbf00-c8c4-4b88-8caf-267a996ca001)
[EFI.zip](https://github.com/user-attachments/files/18265295/EFI.zip)

**Comment by lzhoang2801** [comment]
Do it https://dortania.github.io/OpenCore-Install-Guide/extras/kaslr-fix.html#using-devirtualisemmio

**Comment by kamin067** [comment]
With sonoma i am getting black screen after verbose loading

**Comment by lzhoang2801** [comment]
Disable NootedRed kext first

**Comment by kamin067** [comment]
and that is done by turning bolean to false right?

**Comment by lzhoang2801** [comment]
Did you read guide?
