### ISSUE TITLE
GPU not supported

### ISSUE THREAD

**Issue by oiutretu** [lzhoang2801/OpCore-Simplify#91]
My GPU was working when i first install hackintosh(Sonoma) but i can't find the efi for sequoia (and i deleted the sonoma efi) i used but it says unsupported gpu please help! 
report file: 
[Report.json](https://github.com/user-attachments/files/18266328/Report.json)

**Comment by lzhoang2801** [comment]
Are you sure it's working? Could you provide further evidence? 
You've achieved something that many other developers are trying to get working, as seen here: [https://www.insanelymac.com/forum/topic/358305-80-solved-iris-xe-igpu-on-tiger-lake-successfully-loaded-icllp-frambuffer-and-vram-also-recognizes-1536mb-however-some-issues/](https://www.google.com/url?sa=E&q=https%3A%2F%2Fwww.insanelymac.com%2Fforum%2Ftopic%2F358305-80-solved-iris-xe-igpu-on-tiger-lake-successfully-loaded-icllp-frambuffer-and-vram-also-recognizes-1536mb-however-some-issues%2F)

**Comment by oiutretu** [comment]
here is my gpu info
![image](https://github.com/user-attachments/assets/760307e4-85fc-4d59-a059-23cd3e8c6687)
link where i download my driver
https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html

**Comment by oiutretu** [comment]
more info on gpu
![image](https://github.com/user-attachments/assets/6833c7a6-1cb5-41fd-a3d2-09c88186045a)

**Comment by lzhoang2801** [comment]
Are you understanding that I need information for macOS? What's the value of additional information about it supporting Windows?

**Comment by oiutretu** [comment]
i currently don't have evidence that i once ran macOS and i don't understand your last comment since i left it 2 years ago
this maybe
https://elitemacx86.com/threads/how-to-enable-intel-hd-and-uhd-graphics-on-macos-intel-framebuffer-patching-guide.931/
https://elitemacx86.com/threads/how-to-enable-intel-uhd-graphics-comet-lake-on-macos-big-sur-and-later.897/

**Comment by oiutretu** [comment]
can you give me another version that supports my gpu please

**Comment by oiutretu** [comment]
Hello?

**Comment by oiutretu** [comment]
it's working on 4 mb

**Comment by lzhoang2801** [comment]
That's why the GPU isn't supported. Don't bother me with useless findings.
